language: java
jdk:
  - openjdk11

install: 
  - ant deps

script: 
  - ant integracion-continua

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - jbudnechky@fi.uba.ar
    on_failure: always