
language: java
jdk:
  - oraclejdk8
  - openjdk11
  - openjdk12

install: ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - jbudnechky@fi.uba.ar
    on_failure: always